In [1]:
import numpy as np

In [5]:
my_arr = np.arange(100000)
# print(my_arr)
my_arr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [9]:
my_list = list(range(10000))
# my_list

In [8]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 4 ms


In [10]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 16.2 ms


## Numpy ndarray

In [11]:
data = np.random.randn(2,3)
data

array([[-0.94777968, -0.49742052, -1.30546796],
       [ 0.61438617, -0.92022776,  1.71480296]])

In [12]:
data*10

array([[ -9.47779681,  -4.97420516, -13.05467958],
       [  6.14386172,  -9.20227764,  17.14802962]])

In [13]:
data+data

array([[-1.89555936, -0.99484103, -2.61093592],
       [ 1.22877234, -1.84045553,  3.42960592]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [16]:
# creating ndarrays
data1 =[6,7,2,3,4]
arr1 = np.array(data1)
arr1

array([6, 7, 2, 3, 4])

In [21]:
data2 = [[1,2,3],[4,5,9]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 9]])

In [19]:
print("Dimension of array: ",arr2.ndim)
print(arr2.shape)

Dimension of array:  2
(2, 3)


In [22]:
print(arr1.dtype,arr2.dtype)

int32 int32


In [23]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
abc = np.empty((2, 3, 2))
abc

array([[[9.14684356e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 4.32026133e-061]],

       [[4.49965847e+174, 5.10272223e-066],
        [1.54666993e+185, 1.17470962e+165],
        [6.82490993e-067, 1.45162562e-051]]])

In [31]:
np.arange(14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [33]:
arr1 = np.array([2,3,1], dtype=np.float64)
arr1

array([2., 3., 1.])

In [35]:
arr = arr1.astype(np.int32)
arr

array([2, 3, 1])

In [37]:
empty_uint32 = np.empty(8,dtype='u4')
empty_uint32

array([         0,          0,  141823280,        431,          0,
                0, 2147483648,          0], dtype=uint32)

## Arithmetic with NumPy Arrays

In [38]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [41]:
print("Multiplication",arr*arr)
print("Substraction",arr-arr)

Multiplication [[ 1.  4.  9.]
 [16. 25. 36.]]
Substraction [[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
print(1/arr)
print(arr**2)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [47]:
arr2 = np.array([[0.,2.,1.],[7.,5.,9.]])
print(arr2)
arr2>arr

[[0. 2. 1.]
 [7. 5. 9.]]


array([[False, False, False],
       [ True, False,  True]])

# Basic Indexing and Slicing

In [49]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
print("Accesing Specific element: ",arr[5])
#lower bound included and upper bound excluded in slicing
print("Slicing into small array: ",arr[5:8]) 

Accesing Specific element:  5
Slicing into small array:  [5 6 7]


In [57]:
#assigning value to a slice of arr
arr[5:8] = 12
print(arr)
arr[5:8] = [3,5,1]
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]
[0 1 2 3 4 3 5 1 8 9]


In [59]:
#assigning this way will point same element and change 
#in any one will affect the other one
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 34
print(arr)

[3 5 1]
[ 0  1  2  3  4  3 34  1  8  9]


In [60]:
arr_slice = arr[5:8].copy()
print(arr_slice)
arr_slice[1] = 5
print(arr_slice)
print(arr)

[ 3 34  1]
[3 5 1]
[ 0  1  2  3  4  3 34  1  8  9]


In [64]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0][2])
print(arr2d[0,2])

[7 8 9]
3
3


In [66]:
print(arr2d)
print(arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [68]:
print(arr2d[:2, 2])
print(arr2d[:, :1])

[3 6]
[[1]
 [4]
 [7]]


In [69]:
#assigning value to slice pof a 2d array
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# Boolean Indexing

In [70]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.21843437  1.72083856 -0.58672534  0.54616828]
 [-2.21346483  0.7436051   1.48261988  0.27919707]
 [-0.26605985 -2.33823642 -1.12444231  1.04152361]
 [ 0.54606966  0.37864058 -0.47877217  0.78628512]
 [ 1.85171089  0.39422109 -0.00735478  2.2470623 ]
 [ 0.71870219  0.74401251 -0.84282903 -0.0068882 ]
 [ 0.59223952 -0.717202   -0.65363583  0.23646856]]


In [71]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [72]:
data[names == "Bob"]

array([[-0.21843437,  1.72083856, -0.58672534,  0.54616828],
       [ 0.54606966,  0.37864058, -0.47877217,  0.78628512]])

In [74]:
data[data<0] = 0
data

array([[0.        , 1.72083856, 0.        , 0.54616828],
       [0.        , 0.7436051 , 1.48261988, 0.27919707],
       [0.        , 0.        , 0.        , 1.04152361],
       [0.54606966, 0.37864058, 0.        , 0.78628512],
       [1.85171089, 0.39422109, 0.        , 2.2470623 ],
       [0.71870219, 0.74401251, 0.        , 0.        ],
       [0.59223952, 0.        , 0.        , 0.23646856]])